import { type NextPage } from "next";
import NextError from "next/error";
import Head from "next/head";

import { trpc } from "../../utils/trpc";

const Artists: NextPage = () => {
  const artistsQuery = trpc.artist.getAll.useQuery();

  if (artistsQuery.error) {
    return (
      <NextError
        title={artistsQuery.error.message}
        statusCode={artistsQuery.error.data?.httpStatus ?? 500}
      />
    );
  }

  if (artistsQuery.status !== "success") {
    return <>Loading...</>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Artists
          </h1>
          {/* Show artist in a table list */}
          <table className="table-auto text-white">
            <thead>
              <tr>
                <th className="px-4 py-2">Name</th>
                <th className="px-4 py-2">Link</th>
              </tr>
            </thead>
            <tbody>
              {artistsQuery.data?.map((artist) => (
                <tr key={artist.id}>
                  <td className="border px-4 py-2">{artist.name}</td>
                  <td className="border px-4 py-2">
                    <a className="text-blue-500" href={`/artists/${artist.id}`}>
                      Add Lyrics →
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Artists;
