import { type NextPage } from "next";
import NextError from "next/error";
import Head from "next/head";
import { useRouter } from "next/router";

import { trpc } from "../../utils/trpc";

const Song: NextPage = () => {
  const id = useRouter().query.id as string;
  const songQuery = trpc.song.getById.useQuery({ id });

  if (songQuery.error) {
    return (
      <NextError
        title={songQuery.error.message}
        statusCode={songQuery.error.data?.httpStatus ?? 500}
      />
    );
  }

  if (songQuery.status !== "success") {
    return <>Loading...</>;
  }

  return (
    <>
      <Head>
        <title>{songQuery.data?.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {songQuery.data?.title}
          </h1>
          <div className="rounded-xl border-2 border-white/20 p-4 text-center text-2xl text-white">
            <p>{songQuery.data?.lyrics}</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Song;
